// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChl3POx3M_MOPtesfW2zAoYvJYeCb0jZ4',
    appId: '1:401048890551:web:e67734c24f38e7db7e3132',
    messagingSenderId: '401048890551',
    projectId: 'login-app-d12bc',
    authDomain: 'login-app-d12bc.firebaseapp.com',
    storageBucket: 'login-app-d12bc.firebasestorage.app',
    measurementId: 'G-2V51NP5YN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuMeTBtHWob3lOwm91CEc8UUnWUDt_dXo',
    appId: '1:401048890551:android:3e9b8340f096daf47e3132',
    messagingSenderId: '401048890551',
    projectId: 'login-app-d12bc',
    storageBucket: 'login-app-d12bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDToPGNUz_ydNfeKr2oRPH5m-VgTbI_qiE',
    appId: '1:401048890551:ios:2875009ec4b89a497e3132',
    messagingSenderId: '401048890551',
    projectId: 'login-app-d12bc',
    storageBucket: 'login-app-d12bc.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );
}
